use_frameworks!

platform :ios, '10.0'

target 'TestStrlengs_Example' do
  pod 'TestStrlengs', :path => '../'

  target 'TestStrlengs_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
